name: GitHub Pages

on:
  push:
    branches:
      - "**"

  release:
    types: [published]

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Change tag to the latest commit
        if: ${{ github.ref_type == 'tag' }}
        run: |
          git tag -f $GITHUB_REF_NAME

      - name: Get latest stable release
        id: stable_release
        continue-on-error: true
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: ${{ github.repository_owner }}
          repo: cleanlab-docs-ci-fix
          excludes: prerelease, draft

      - name: Create latest_release.txt file
        if: ${{ steps.stable_release.outcome == 'success' }}
        run: echo ${{ steps.stable_release.outputs.release }} > cleanlab-docs/latest_release.txt

      - name: Update OpenGraph URLs in HTML files
        env:
          REF_URL_SEGMENT: ${{ (github.ref_type == 'tag' && steps.stable_release.outcome == 'success') && 'stable' || github.ref_name }}
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '(<meta property="og:url" content="https?:\/\/[^\/]+\/)([^"]+")'
          replace: '$1${{ env.REF_URL_SEGMENT }}/$2'
          include: "cleanlab-docs/**/*.html"
          regex: true
      
      - name: Deploy
        if: ${{ (github.ref == 'refs/heads/master') || (github.ref_type == 'tag') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # publish_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cleanlab-docs
          publish_branch: gh-pages
          keep_files: true
          exclude_assets: ""

      - uses: actions/upload-artifact@v3
        with:
          name: docs-html
          path: cleanlab-docs
          retention-days: 1 # don't need this except in link checking step below

  links:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: docs-html
          path: cleanlab-docs
      - uses: anishathalye/proof-html@v1
        with:
          directory: ./cleanlab-docs
          external_only: true
          url_ignore_re: |
            ^https://pradyunsg.me/
            ^https://keras.io/
